#!/bin/bash

DBPATH=$1
DBPORT=$2
LAUNCH=$3

if [ -z "$DBPORT" ]
then
  DBPORT=27017
fi

if [ -z "$DBPATH" ]
then
  echo "Need to give a path for mongodb instance as script argument"
  exit 1
else
  if ! [ -z "`lsof -Pi :$DBPORT | grep $DBPORT`" ]
  then
    echo "Port $DBPORT is already in use, try giving a different port as second argument"
    exit 1
  fi
fi

mkdir -p $DBPATH
mkdir -p $DBPATH/db
mkdir -p $DBPATH/socket

DBHOSTFILE="$DBPATH/db.log"

echo -e "net:\n   unixDomainSocket:\n      pathPrefix: $DBPATH/socket\n   bindIp: 0.0.0.0\n   port:   $DBPORT\n" > $DBPATH/db.cfg

echo "================================================================================" &>> $DBHOSTFILE
echo "================================================================================" &>> $DBHOSTFILE
echo "[ $(date +'%Y-%m-%d %H:%M:%S.%5N') ] Log starting from new 'mongod' instance" &>> $DBHOSTFILE
echo "================================================================================" &>> $DBHOSTFILE

if [ ! -z "$(command -v numactl)" ]; then
  launcher="numactl --interleave=all "
else
  launcher=""
fi

mongodcommand="${launcher}mongod --dbpath $DBPATH/db/ --config $DBPATH/db.cfg &>> $DBHOSTFILE &"

eval "$mongodcommand"

# When using startdb, we need PID to track the launched process
echo "$!"

