#!/bin/bash

# Avoid capturing AdaptiveMD's mongod utilities
mongods=`ps faux | grep "mongod" | grep -v "grep" | grep -v "amongod" | grep -v "list_mongods"`
echo "Current mongod processes:"
printf '%s\n' "${mongods[@]}"
