#!/bin/bash

WORKERID="$OMPI_COMM_WORLD_RANK"
WORKERLOG="workers/adaptivemd.worker.${WORKERID}.log"

echo "Worker$WORKERID says hello: $(date +'%Y-%m-%d %H:%M:%S.%5N')" >> $WORKERLOG

PROJNAME="$1"
ADMD_DBURL="$2"
NWORKERS="$3"

workercommand="adaptivemdworker $PROJNAME --dblocation $ADMD_DBURL -v &>> $WORKERLOG"
echo "Worker$WORKERID command:" >> $WORKERLOG

echo "Worker$WORKERID starts: $(date +'%Y-%m-%d %H:%M:%S.%5N')" >> $WORKERLOG
echo "$workercommand" >> $WORKERLOG
eval "$workercommand"
echo "Worker$WORKERID stops: $(date +'%Y-%m-%d %H:%M:%S.%5N')" >> $WORKERLOG
